#!/usr/bin/env bash

set -eo pipefail

# Generate and sign all UKI files
declare -g SIGN_ALL=1

# Generate all UKI files
declare -g ALL=1

# Set of kernel unames/paths
declare -A kernels

# An array of sorted pkgbases
declare -a sorted_pkgbases=()

while read -r line; do
  case "$line" in
    usr/bin/booster | usr/bin/booster-um | usr/bin/ukify | \
    usr/lib/booster/* | usr/lib/firmware/* | usr/src/*/dkms.conf)
      (( SIGN_ALL )) && SIGN_ALL=0
      ;;
    usr/lib/modules/*/vmlinuz | usr/lib/modules/*/extramodules/*)
      if (( SIGN_ALL == 1 && ALL == 1 )); then
        modules_suffix="${line#usr/lib/modules/}"
        uname="${modules_suffix%%/*}"
        kernels["$uname"]=1
      fi
      ;;
    *)
      (( ALL )) && ALL=0
      ;;
  esac
done

# Generate and sign UKI files for all kernels
if (( SIGN_ALL == 0 )); then exec booster-um -G; fi

# Sbctl hook should sign the UKI file if it already exists in database
# Disable the signing inside the booster-um
export ALWAYS_SIGN=1

# Generate UKI files for all kernels
if (( ALL == 0 )); then exec booster-um -G; fi

# Get the sorted pkgbases
mapfile -t sorted_pkgbases < <(
  for uname in "${!kernels[@]}"; do
    pkgbase_file="/usr/lib/modules/${uname}/pkgbase"

    if ! pacman -Qqo -- "$pkgbase_file" > /dev/null 2>&1; then
      continue
    fi

    read -r pkgbase < "$pkgbase_file"
    printf '%s\n' "$pkgbase"
  done | sort
)

# Genearate UKI files for updated kernels
exec booster-um -u "${sorted_pkgbases[@]}"