#!/usr/bin/env bash

set -e

all=0
kernels=()

while read -r line; do
  if [[ ${line} != usr/lib/modules/* ]]; then
    all=1
    break
  fi

  kernels+=("/${line%/vmlinuz}")
done

# Generate UKI files for all kernels
if [ "${all}" -eq "1" ]; then
  booster-um -U
  exit
fi

for kernel in "${kernels[@]}"; do
  if ! pacman -Qqo "${kernel}/pkgbase" > /dev/null 2>&1; then
    # if pkgbase does not belong to any package then skip this kernel
    continue
  fi
  read -r pkgbase < "${kernel}/pkgbase"

  uname="${kernel##/usr/lib/modules/}"

  # Genearate UKI file for updated kernel
  booster-um -u "$pkgbase" "$uname"
done
