#!/usr/bin/env bash

set -e

kernels=()

while read -r line; do
  kernels+=("/${line%/vmlinuz}")
done

for kernel in "${kernels[@]}"; do
  if ! pacman -Qqo "${kernel}/pkgbase" > /dev/null 2>&1; then
    # if pkgbase does not belong to any package then skip this kernel
    continue
  fi
  read -r pkgbase < "${kernel}/pkgbase"

  # Remove booster initramfs, vmlinuz and UKI kernel files
  booster-um -r "$pkgbase"
done
