#!/usr/bin/env bash

set -e

# Generates one UKI
_generate_uki() {
  # arguments
  local pkgbase="$1"

  # systemd-ukify paths
  local CMDLINE SPLASH UNAME VMLINUZ UKI INITRD
  UNAME="$2"

  echo -e "${B}==>${NC} Generating UKI for ${G}${pkgbase}${NC}..."

  # vmlinuz path
  VMLINUZ="/boot/vmlinuz-${pkgbase}"

  # booster initramfs
  local booster_inits=("/boot/booster-${pkgbase}.img")
  if _should_generate_fallback; then
    booster_inits+=("/boot/booster-${pkgbase}-fallback.img")
  fi

  # Return if required initramfs files do not exist
  if ! stat -- "${booster_inits[@]}" > /dev/null 2>&1 || [[ ! -e $VMLINUZ ]]; then
    echo -e "${R}==>${NC} Unable to generate UKI for ${R}${pkgbase}${NC}..."
    return
  fi

  # Fix the initramfs file permissions if necessary
  [[ ! $(stat -c %a "${booster_inits[@]}" | grep -w "600" | wc -l) -eq "${#booster_inits[@]}" ]] && \
  chmod -f 600 -- "${booster_inits[@]}"

  # cmdline file path or cmdline kernel parameters
  CMDLINE="$(_get_cmdline $pkgbase)"

  # splash file
  SPLASH="$(_get_splash_path)"

  # microcodes
  local -a microcodes
  mapfile -d '' microcodes < <(find /boot -name '*-ucode.img' -type f -print0)

  # initrd temp path
  INITRD="$(mktemp -t 'initrd.XXXXXX')"

  # UKI file path, create EFI dir if it doesn't exist
  [[ ! -e $EFI_DIR ]] && mkdir -p "$EFI_DIR"
  local uki_path="${EFI_DIR}/arch-${pkgbase}"

  local -a sign_args=()
  if [[ $sbsign -eq 1 ]] && _should_sign_uki; then
    local pcr_banks="$(_get_sbsign_property pcr_banks)"
    local pcr_private_key="$(_get_sbsign_property pcr_private_key)"
    local pcr_public_key="$(_get_sbsign_property pcr_public_key)"
    local secureboot_private_key="$(_get_sbsign_property secureboot_private_key)"
    local secureboot_certificate="$(_get_sbsign_property secureboot_certificate)"

    sign_args+=(${pcr_banks:+"--pcr-banks=$pcr_banks"} \
                ${pcr_private_key:+"--pcr-private-key=$pcr_private_key"} \
                ${pcr_public_key:+"--pcr-public-key=$pcr_public_key"} \
                ${secureboot_private_key:+"--secureboot-private-key=$secureboot_private_key"} \
                ${secureboot_certificate:+"--secureboot-certificate=$secureboot_certificate"})
  fi

  for init_id in "${!booster_inits[@]}"; do
    local booster_initramfs="${booster_inits[init_id]}"

    # Create one initrd
    cat -- "${microcodes[@]}" "$booster_initramfs" > "$INITRD"

    # Set UKI fallback path
    [[ $init_id -gt 0 ]] && uki_path="${uki_path}-fallback"

    # Set the UKI file with .efi exstension
    UKI="${uki_path}.efi"

    # Build the UKI file, sign it and create EFI entry
    /usr/lib/systemd/ukify build \
      --uname="$UNAME" \
      --linux="$VMLINUZ" \
      --initrd="$INITRD" \
      ${CMDLINE:+"--cmdline=$CMDLINE"} \
      ${SPLASH:+"--splash=$SPLASH"} "${sign_args[@]}" \
      --output="$UKI" | tail -n 1 && \
      _sign_uki "$UKI" && _create_efi_entry "$UKI"

    # Remove the old initrd after creating the UKI file
    rm -f "$INITRD"
  done

  # Remove the leftovers (vmlinuz, booster initramfs and other files)
  _remove_leftovers "$pkgbase" 1
}

# Generates UKI file for specified kernel package name
_generate_kernel_uki() {
  local pkgbase="$1"
  _check_pkgbase "$pkgbase"

  # Get the index of pkgbase
  index="$(_get_array_index pkgbases $pkgbase)"
  local kernel="${kernels[$index]}"
  local uname="$(_get_kernel_uname $kernel)"

  # Generate initramfs
  _generate_initramfs "$pkgbase" "$uname" || return

  # Generate and sign UKI file
  _generate_uki "$pkgbase" "$uname"
}

# Generates UKI files for all installed kernels
_generate_all_uki() {
  local uname
  for kernel in "${kernels[@]}"; do
    read -r pkgbase < "${kernel}/pkgbase"
    uname="$(_get_kernel_uname $kernel)"

    # Generate and sign UKI file
    _generate_uki "$pkgbase" "$uname"
  done
}

# Generates initramfs and fallback initramfs
_regenerate_images() {
  local pids=()
  local pkgbase
  for kernel in "${kernels[@]}"; do
    read -r pkgbase < "${kernel}/pkgbase"
    uname="$(_get_kernel_uname $kernel)"
    _generate_initramfs "$pkgbase" "$uname" & pids+=( $! )
  done

  # Wait for all background jobs
  for pid in "${pids[@]}"; do
    wait "$pid"
  done
}

# Generate initramfs for specified kernel path
_generate_initramfs() {
  local pkgbase="$1"
  local uname="$2"

  echo -e "${B}==>${NC} Generating initramfs for ${G}${pkgbase}${NC}..."

  # Install the vmlinuz
  if ! _install_vmlinuz "$pkgbase" "$uname"; then return 1; fi

  # Set the booster initramfs file path
  local initramfs="/boot/booster-${pkgbase}.img"

  # Generate initramfs
  if ! booster build --force --kernel-version "$uname" "$initramfs"; then
    echo -e "${R}==>${NC} Unable to generate initramfs for ${R}${pkgbase}${NC}..."
    _remove_leftovers "$pkgbase" 1
    return 1
  fi

  # Set the permission to 600 for the initramfs file
  chmod -f 600 -- "$initramfs"

  # Generate the fallback initramfs
  _generate_fallback_initramfs "$pkgbase" "$uname"
}

# Installs the vmlinuz
_install_vmlinuz() {
  local pkgbase="$1"
  local uname="$2"

  local boot_vmlinuz="/boot/vmlinuz-${pkgbase}"
  [[ -e $boot_vmlinuz ]] && return

  local kernel="/usr/lib/modules/${uname}"
  local module_vmlinuz="${kernel}/vmlinuz"
  if [[ ! -e $module_vmlinuz ]]; then
    echo -e "${R}==>${NC} Unable to find vmlinuz for ${R}${pkgbase}${NC}..."
    return 1
  fi

  # Install the vmlinuz
  install -Dm644 "$module_vmlinuz" "$boot_vmlinuz"
}

# Generates fallback initramfs
_generate_fallback_initramfs() {
  if ! _should_generate_fallback; then return; fi

  local uname pkgbase fallback_initramfs
  pkgbase="$1"
  uname="$2"
  fallback_initramfs="/boot/booster-${pkgbase}-fallback.img"

  # Generate the fallback initramfs
  booster build --force --universal --kernel-version "$uname" "$fallback_initramfs" && \
  chmod -f 600 -- "$fallback_initramfs"
}

# Regenerates UKI files for all installed kernels
_regenerate_all() {
  echo -e "${B}::${W} Generating initramfs for all installed kernels...${NC}"
  _regenerate_images || :
  echo -e "${B}::${W} Generating UKI files for all installed kernels...${NC}"
  _generate_all_uki
}
