#!/usr/bin/env bash

set -x

# Removes the cmdline for specified kernel
_remove_cmdline() {
  local pkgbase="$1"

  # cmdline path
  local cmdline_path="/etc/kernel/${pkgbase}.cmdline"

  # If the cmdline path exists, remove it
  if [[ -e $cmdline_path ]]; then
    echo -e "${Y}==>${NC} Removing cmdline ${Y}$cmdline_path${NC}..." >&2
    rm -f "cmdline_path"
  fi
}

# Removes the leftovers form /boot
_remove_boot_leftovers() {
  local pkgbase="$1"

  # Remove leftovers from /boot dir
  rm -f /boot/.booster*
  rm -f /boot/vmlinuz-"${pkgbase}"
  rm -f /boot/booster-"${pkgbase}"{-fallback.img,.img}
}

# Removes other leftovers (efi entries, cmdlines, fallback images)
_remove_other_leftovers() {
  local pkgbase="$1"

  local uki="${EFI_DIR}/arch-${pkgbase}.efi"
  local fallback_uki="${EFI_DIR}/arch-${pkgbase}-fallback.efi"

  # If the package doesn't exist, remove UKI and leftovers
  if ! _pkgbase_exists "$pkgbase"; then
    _remove_from_db "$uki"
    _remove_from_db "$fallback_uki"
    _remove_efi_entry "$uki"
    _remove_efi_entry "$fallback_uki"
    _remove_cmdline "$pkgbase"
    rm -f "$uki" "$fallback_uki"
    return
  fi

  # Remove fallback UKI files in ESP if fallback generation is not enabled
  if ! _should_generate_fallback && [[ -e $fallback_uki ]]; then
    _remove_from_db "$fallback_uki"
    _remove_efi_entry "$fallback_uki" && local fallback_removed=1
    rm -f "$fallback_uki"
  fi

  # Remove efi entry if efistub is not enabled
  if ! _should_create_efi_entry; then
    _remove_efi_entry "$uki"
    [[ $fallback_removed -eq 1 ]] && return
    _remove_efi_entry "$fallback_uki"
  fi

  # Remove the pkgbase cmdline if cmdline per kernel is not enabled
  if ! _cmdline_per_kernel; then
    _remove_cmdline "$pkgbase"
  fi
}

# Removes all known vmlinuz and initramfs files for specified kernel
_remove_leftovers() {
  local pkgbase="$1"

  if ! _should_remove_leftovers; then return; fi

  # Remove leftovers from /boot dir
  _remove_boot_leftovers "$pkgbase"

  [[ ${2:-0} -eq 0 ]] && return

  # Remove other leftovers (efi entries, cmdlines, fallback images)
  _remove_other_leftovers "$pkgbase"
}

# Removes all known UKI files from esp/EFI/Linux dir
_remove_all_uki() {
  echo -e "${Y}::${NC} Removing ${Y}all known UKI files${NC}..."
  for pkgbase in "${pkgbases[@]}"; do
    # Remove the UKI file, vmlinuz and initramfs
    _remove_uki "$pkgbase"
  done
}

# Removes esp/EFI/Linux dir and all files from the sbctl database
_cleanup() {
  shopt -s nullglob

  echo -e "${Y}::${NC} Removing ${Y}all initramfs*, booster*, vmlinuz*${NC} files from ${Y}/boot${NC}..."

  # Remove all initramfs-*, booster-*, vmlinuz-* files
  rm -f /boot/{.initrd,initramfs,booster,vmlinuz}*

  # Store all EFI files in array
  local efi_files=("${EFI_DIR}"/*.efi)

  for efi_file in "${efi_files[@]}"; do
    # Remove the file from sbctl database
    _remove_from_db "$efi_file"

    # Remove EFI entries
    _remove_efi_entry "$efi_file"
  done

  # Remove esp/EFI/Linux dir
  echo -e "${Y}==>${NC} Removing ${Y}${EFI_DIR}${NC} dir..."
  rm -rf "$EFI_DIR"

  # Remove *.cmdline files
  echo -e "${Y}==>${NC} Removing all ${Y}.cmdline${NC} files from ${Y}/etc/kernel${NC}..."
  rm -f "/etc/kernel/*.cmdline"

  shopt -u nullglob
}

# Removes UKI file for specified kernel
_remove_uki() {
  local pkgbase="$1"
  _check_pkgbase "$pkgbase"

  # Store all UKI files in array
  readarray -t uki_files < <(find "${EFI_DIR}" \
    -type f \
    -name "arch-${pkgbase}.efi" -o \
    -name "arch-${pkgbase}-fallback.efi" 2> /dev/null)

  for uki in "${uki_files[@]}"; do
    # Remove the UKI file from sbctl database
    echo -e "${Y}==>${NC} Removing ${Y}${uki}${NC} file..."
    _remove_from_db "$uki"

    # Remove the UKI file
    rm -f "$uki"

    # Remove the cmdline file
    rm -f "/etc/kernel/${pkgbase}.cmdline"

    # Remove the EFI entry
    _remove_efi_entry "$uki"
  done

  # Remove the leftovers
  _remove_leftovers "$pkgbase"
}

# Removes UKI files and other leftovers
# This function is called from PostTransaction libalpm Remove hook
_post_transaction_remove() {
  shopt -s nullglob

  local -a found_pkgbases=()
  #local -a removed_pkgbases=()

  # Get all known UKI files from the EFI dir, e.g.: /efi/EFI/Linux/arch-linux.efi
  local uki_files=("${EFI_DIR}"/arch-*.efi)

  # Find all known pkgbases from the uki file path name
  for uki in "${uki_files[@]}"; do
    local pkgbase=$(_get_pkgbase_from_path "$uki")
    pkgbase="${pkgbase%-fallback}"
    found_pkgbases+=("$pkgbase")
  done

  # Find the remove pkgbases
  removed_pkgbases=("$(echo ${pkgbases[@]} ${found_pkgbases[@]} | tr ' ' '\n' | sort | uniq -u)")

  # For each removed pkgbase, remove the UKI file and other leftovers
  for pkgbase in "${removed_pkgbases[@]}"; do
    # Remove the leftovers from /boot dir
    _remove_boot_leftovers "$pkgbase"

    # Remove other leftovers (efi entries, cmdlines, fallback images)
    _remove_other_leftovers "$pkgbase"
  done

  shopt -u nullglob
}
